/**
 * Derive the first name the writer signs messages with from the user row.
 * Extracted from routes/followupOpen.ts (Speed pass, 2026-07-16) so the
 * hourly pre-generation pass and the token-authed open route resolve the
 * SAME name — a follow-up pre-generated by the cron must read identically
 * to one generated at click time.
 */
export function senderNameFromUser(name: string | null, email: string): string {
  if (name?.trim()) return name.trim().split(/\s+/)[0]!;
  return email.split("@")[0] ?? "there";
}
