// AUTO-GENERATED by ticket-prospect-multi-format-upload.
// parseUploadedUrls — extract URLs from txt/csv/tsv/xlsx/xls files.
//
// Dispatches on file extension. Text formats are read directly; xlsx
// and xls are parsed via SheetJS, with each sheet converted to CSV
// before regex-extraction. Returns deduplicated URLs in first-seen
// order plus any warnings to surface to the user.

import * as XLSX from "xlsx";

const URL_RE = /https?:\/\/[^\s,;|"'<>{}]+/g;
const TRAILING_PUNCT_RE = /[.,;:!?)\]>]+$/;

export interface ParseUploadedUrlsResult {
  urls: string[];
  warnings: string[];
}

export async function parseUploadedUrls(
  file: File,
): Promise<ParseUploadedUrlsResult> {
  const ext = (file.name.split(".").pop() ?? "").toLowerCase();
  const warnings: string[] = [];
  let text: string;

  switch (ext) {
    case "txt":
    case "csv":
    case "tsv": {
      text = await file.text();
      break;
    }
    case "xlsx":
    case "xls": {
      try {
        const buf = await file.arrayBuffer();
        const wb = XLSX.read(buf, { type: "array" });
        text = wb.SheetNames.map((name) =>
          XLSX.utils.sheet_to_csv(wb.Sheets[name] ?? {}),
        ).join("\n");
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          urls: [],
          warnings: [`Could not read ${file.name}: ${msg}`],
        };
      }
      break;
    }
    default: {
      // Unknown extension. Best-effort: try as text. Warn user.
      try {
        text = await file.text();
        warnings.push(
          `Unknown file extension ".${ext}" in ${file.name}; read as plain text. Supported: .txt, .csv, .tsv, .xlsx, .xls.`,
        );
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          urls: [],
          warnings: [`Could not read ${file.name}: ${msg}`],
        };
      }
    }
  }

  const matches = text.match(URL_RE) ?? [];
  const cleaned = matches.map((u) => u.replace(TRAILING_PUNCT_RE, ""));

  const seen = new Set<string>();
  const unique: string[] = [];
  for (const u of cleaned) {
    if (!seen.has(u)) {
      seen.add(u);
      unique.push(u);
    }
  }

  if (unique.length === 0) {
    warnings.push(
      `No URLs found in ${file.name}. The file is supported but contained no http(s) URLs.`,
    );
  }

  return { urls: unique, warnings };
}
